### ISSUE TITLE
[FEATURE]Responsiveness of homepage

### ISSUE THREAD

**Issue by Soulpurr** [WebXDAO/WebXDAO.github.io#364] opened 2023-05-25 15:23 UTC
### Detailed description

Homepage is not responsive. I would like to work on that.
Pls assign this issue to me under gssoc23

### Context

Responsive is must now a days

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment] 2023-05-25 16:17
Hello :wave: 
Duplicate of #331 #333 #350

**Comment by Soulpurr** [comment] 2023-05-25 16:20
Yea just raised it as it's still not completed

**Comment by mkubdev** [comment] 2023-05-25 16:23
> Yea just raised it as it's still not completed

Yes, issues are assigned in waiting for their PR. The live website still isn't responsive yet 😄

**Comment by Soulpurr** [comment] 2023-05-25 16:24
So how long will you wait before unassigning 😂

**Comment by vinzvinci** [comment] 2023-05-25 16:27
> So how long will you wait before unassigning 😂

If a contributor doesn't provide an update on an issue within 2-3 days, we can unassigned. Please wait for now ^^

**Comment by Soulpurr** [comment] 2023-05-25 16:39
Okk

**Comment by Anmol-Baranwal** [comment] 2023-06-26 07:15
I am closing this issue since this is tagged as duplicate, you can reopen if you feel otherwise.

> One should provide clear descriptions in the issue on what you can contribute in the responsiveness.

**Closed by Anmol-Baranwal** 2023-06-26 07:15 UTC
Labels: duplicate, enhancement
