### ISSUE TITLE
[FEATURE] Add Projects Page as per v3 re-branding design [GSSoC' 23]

### ISSUE THREAD

**Issue by MAYANKpandey14** [WebXDAO/WebXDAO.github.io#349] opened 2023-05-24 19:34 UTC
### Create a completely responsive Project page as per the figma design.

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/94740455/92f12a13-a6dd-4831-8f29-9dbb6f5d3d0f)

### Key points of Focus : -

- Responsiveness
- Achieving the design as provided by the Figma file

### Additional information

Already contributed by creating the footer section ( Responsive but I forgot to refer to figma design) #328 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Preetam078** [comment] 2023-05-25 05:22
hi member 
-> for the above issue I will create a new page for the **projectsToCheck.js** and a component for the **Card.js** ( fileName could vary ) in the screenshot

-> I will use tailwind CSS for styling and the **Card.js** component

-> The **Card.js** component  will be render multiple times inside the **projectsToCheck.js** page using Javascript Map function (higher order function ) as per the requirements,  

-> The values inside the **Card.js** component will be store using props and destructuring 

please assign this issue to me under the GSSoC 23. it will be helpful.

**Comment by MAYANKpandey14** [comment] 2023-05-25 05:33
Really appreciate your spirit. However I have reported this issue for myself to work on

**Comment by MAYANKpandey14** [comment] 2023-05-25 05:34
Quick advice : Kindly find issue and report them to work on them.

**Comment by mkubdev** [comment] 2023-05-25 13:31
Hello @MAYANKpandey14, it's a duplicate of #303, and there is a PR for it #362.
But #362 isn't responsive yet.

We are waiting for others works, and let you know asap.

**Closed** 2023-06-16 17:54 UTC
Labels: duplicate, enhancement
