### ISSUE TITLE
[FEATURE] Want to add hover effect on  the Navbar content

### ISSUE THREAD

**Issue by HimanshuNarware** [WebXDAO/WebXDAO.github.io#423] opened 2023-06-08 12:02 UTC
### Detailed description

I want to add a hover effect on the Navbar content, In Navbar the content is missing hover effects and animation, I want to work on this issue kindly assign me this issue.

### Context

For a better user experience hover and animation is important it shows how well is UI.

### Possible implementation

Want to add a hover effect on the content.
Want to add animation to the  main icon of the navbar

### Additional information

#Screenshot
![173](https://github.com/WebXDAO/WebXDAO.github.io/assets/83147410/abcc739b-95e4-4a51-aae5-0c0aad86668a)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Anmol-Baranwal** [comment] 2023-06-26 07:46
I'm closing this because it's a duplicate of issue #422

**Closed by Anmol-Baranwal** 2023-06-26 07:46 UTC
Labels: enhancement
