### ISSUE TITLE
Adding a cross button in the help card of the guild.xyz page

### ISSUE THREAD

**Issue by Illaf** [WebXDAO/WebXDAO.github.io#462] opened 2023-06-28 02:49 UTC
### Detailed description

In order to close the help card , adding a cross button at the top right corner of the card.
![2023-06-28 (3)](https://github.com/WebXDAO/WebXDAO.github.io/assets/114517448/5462894e-fa73-44b4-8724-a68c23aad874)

### Context

Cross button will help the user to close the card instantly after using it

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Illaf** [comment] 2023-07-03 05:36
@Anmol-Baranwal Please check this issue!

**Comment by Anmol-Baranwal** [comment] 2023-07-03 09:07
I don't believe it would be appropriate since the symbol at the bottom clearly indicates a downward arrow, which typically signifies closing. However, @vinzvinci, please share whether this is necessary or not.

**Comment by mkubdev** [comment] 2023-07-05 13:58
Hi! The issue is from https://github.com/agoraxyz/guild.xyz project! Not our website 🙈
I close!

**Closed by mkubdev** 2023-07-05 13:58 UTC
Labels: enhancement
