### ISSUE TITLE
Building the webX team page

### ISSUE THREAD

**Issue by Illaf** [WebXDAO/WebXDAO.github.io#461] opened 2023-06-28 02:25 UTC
### Detailed description

It seems that the webX team page is not updated with the information and the profile pictures of the team members. 
The profile photos are not available and the links are not valid.

### Context

I will update the information of the team members so that it is available on the website.

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Illaf** [comment] 2023-07-03 05:37
@Anmol-Baranwal Please check this issue!

**Comment by Anmol-Baranwal** [comment] 2023-07-03 09:00
duplicate of #436

**Closed** 2023-07-03 09:01 UTC
Labels: duplicate
