### ISSUE TITLE
[FEATURE] Increase WebX DAO logo size

### ISSUE THREAD

**Issue by vinzvinci** [WebXDAO/WebXDAO.github.io#190] opened 2022-09-21 15:08 UTC
### Detailed description

I find it small 
![image](https://user-images.githubusercontent.com/73097560/191541089-85d124c6-a789-4371-a600-28c74d5a22d4.png)

same with footer 
![image](https://user-images.githubusercontent.com/73097560/191541178-976570e4-b4e8-4373-a6ca-70db4f5be119.png)

### Context

It will be cool to increase the navbar and footer logo :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krshkodes** [comment] 2022-10-01 08:23
@faisalamin001 has opened a PR about it, there for considering it assigned for now

**Comment by Rohitchaudhary13** [comment] 2022-10-02 21:26
Hey!, I opened a PR on this issue!
Please take a look!

**Comment by tarunfy** [comment] 2022-10-07 10:09
@Panquesito7 Can you please assign me this issue, I have created an SVG for our logo and fixed the issue. Its looking great now. Hope you let me do this issue its just a min of work as I have created the logo and tested it 🙂.
<img width="1440" alt="Screenshot 2022-10-07 at 3 36 38 PM" src="https://user-images.githubusercontent.com/51208270/194529729-590c800f-91ce-4af1-a903-4e8edd8bbe5e.png">
^^ See the logo is still not fixed yet.

**Comment by mkubdev** [comment] 2022-10-07 10:27
Hi, you can find our svg logo [here](https://github.com/WebXDAO/brand-assets)! No need to create one.

Actually the issue is being assigned to @Rohitchaudhary13 #217 but need changes.

**Comment by tarunfy** [comment] 2022-10-07 10:49
Hey, @mkubdev there's no SVG logo on that link that you gave 😕, all logos are in png format which will then going to blur out. I would recommend you to please check [this](https://drive.google.com/file/d/1niwfRFfnRNvolK5fPnXC_VS-mCchUiUk/view?usp=sharing) SVG it can be useful 😊.

**Comment by mkubdev** [comment] 2022-10-07 10:52
> Hey, @mkubdev there's no SVG logo on that link that you gave 😕, all logos are in png format which will then going to blur out. I would recommend you to please check [this](https://drive.google.com/file/d/1niwfRFfnRNvolK5fPnXC_VS-mCchUiUk/view?usp=sharing) SVG it can be useful 😊.

You are right! Seem the svg was converted into png once inserted into the markdown... 🤔
Thanks a lot for this logo, maybe you can add it into the brand-asset repository?

**Comment by tarunfy** [comment] 2022-10-07 10:53
<img width="1440" alt="Screenshot 2022-10-07 at 4 22 08 PM" src="https://user-images.githubusercontent.com/51208270/194537262-5bcb3f5d-b64d-4f2e-b6d0-d426947d5c1c.png">
This is how it's looking, clean right? 😃

**Comment by mkubdev** [comment] 2022-10-07 10:53
> <img alt="Screenshot 2022-10-07 at 4 22 08 PM" width="1440" src="https://user-images.githubusercontent.com/51208270/194537262-5bcb3f5d-b64d-4f2e-b6d0-d426947d5c1c.png">
> 
> This is how it's looking, clean right? 😃

Yup super cool!

**Comment by tarunfy** [comment] 2022-10-07 10:55
> > Hey, @mkubdev there's no SVG logo on that link that you gave 😕, all logos are in png format which will then going to blur out. I would recommend you to please check [this](https://drive.google.com/file/d/1niwfRFfnRNvolK5fPnXC_VS-mCchUiUk/view?usp=sharing) SVG it can be useful 😊.
> 
> You are right! Seem the svg was converted into png once inserted into the markdown... 🤔 Thanks a lot for this logo, maybe you can add it into our brand-asset repository?

Okay man, And one more thing, Can I make a pr now for this issue with the right logo in it?! Thanks

**Comment by tarunfy** [comment] 2022-10-07 10:56
> > <img alt="Screenshot 2022-10-07 at 4 22 08 PM" width="1440" src="https://user-images.githubusercontent.com/51208270/194537262-5bcb3f5d-b64d-4f2e-b6d0-d426947d5c1c.png">
> > This is how it's looking, clean right? 😃
> 
> ~Yup super cool!~ Oh wait, the logo has a missed triangle : ![image](https://user-images.githubusercontent.com/50140834/194537594-ce6588bc-c8eb-4f67-bb68-08d5c747f48e.png)

Okay lemme trynna fix it rn.

**Comment by mkubdev** [comment] 2022-10-07 11:08
@tarunfy i sent you an e-mail containing further infos. :)

**Closed** 2022-10-07 12:10 UTC
Labels: enhancement, good first issue
