### ISSUE TITLE
[BUG] Navbar width more than the screen width

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#367] opened 2023-05-25 17:51 UTC
### Description of the bug

The width of the navbar is more than the width of screen which is breaking the UI Design.

### Please add screenshots (if applicable)

https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/a3f538c3-ba6e-4284-bee3-59451d3b3d1d

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s2sharpit** [comment] 2023-05-25 17:51
Hey @vinzvinci @siddhi-244 @darkterminal @mkubdev 

I would like to work on this under GSSoc.
Please add the label [GSSoC23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

**Comment by mkubdev** [comment] 2023-05-25 17:56
Hey 👋🏻 
Well spotted! It's not the navbar, but the hero section.. :eyes:

**Comment by s2sharpit** [comment] 2023-05-25 20:13
> Hey 👋🏻 Well spotted! It's not the navbar, but the hero section.. 👀

Hey 👋, Thanks for pointing that out! It seems like the issue is indeed related to the navbar rather than the hero section. Since it's happening on every page, it's likely that the problem was introduced with the PR titled "mobile navbar fixed" #363 .
Could you please take a look at this and let me know what you think?

**Comment by s2sharpit** [comment] 2023-05-26 05:38
Hey @mkubdev @vinzvinci @darkterminal @siddhi-244 
Can you assign me this issue...

**Comment by s2sharpit** [comment] 2023-05-26 11:49
Please also add gssoc23 label... 😊

**Comment by mkubdev** [comment] 2023-05-26 12:16
> > Hey 👋🏻 Well spotted! It's not the navbar, but the hero section.. 👀
> 
> Hey 👋, Thanks for pointing that out! It seems like the issue is indeed related to the navbar rather than the hero section. Since it's happening on every page, it's likely that the problem was introduced with the PR titled "mobile navbar fixed" #363 . Could you please take a look at this and let me know what you think?

Hi back :wave:, 
After taking a look into the reported issue, I've found a possible root cause and solution. It appears that this bug has been observable since the creation of the hero component as i mentionned. 

The issue seems to be related to the navigation bar present in the layout. Upon removal of the navbar, the issue ceases to exist, implying a potential conflict between these two components.

With this in mind, I would recommend either refactoring the hero component to work compatibly with the navbar, or adjusting the navbar to prevent this interference, depending on your project's requirements and constraints.

As the issue can be mitigated by modifying the current setup, I am going to close this issue for now. This does not mean the conversation has to stop. If further issues arise or if anyone has additional input regarding this matter, please feel free to re-open the issue or create a new one.

Thank you all for your time and valuable input that has led us to this conclusion. Your cooperation in resolving this is greatly appreciated. :)

**Closed** 2023-05-26 12:40 UTC
Labels: bug

**Comment by s2sharpit** [comment] 2023-05-26 13:30
Hey @mkubdev @vinzvinci @darkterminal @siddhi-244
Please add gssoc23 label to this issue....
