### ISSUE TITLE
[BUG] The github button takes you to contributors page instaead of project repo

### ISSUE THREAD

**Issue by clairecharles** [WebXDAO/WebXDAO.github.io#256] opened 2022-10-21 08:24 UTC
### Description of the bug

When you go to the website, you will see a GitHub button. the button is not working as expected.
The button should redirect to the GitHub repo, instead, it goes to the contributor's page

### Please add screenshots (if applicable)

<img width="1346" alt="Screenshot 2022-10-21 at 9 21 03 AM" src="https://user-images.githubusercontent.com/67120042/197148894-23e11a2d-852d-4b6e-80ae-d69850a7f713.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment] 2022-10-21 08:51
Hello Claire ! 👋🏻 

Thanks for the report, this issueseems to be a duplicate of #231 which is currently on-hold.

**Comment by vinzvinci** [comment] 2023-05-13 05:34
This is already done. Thanks!

**Closed by vinzvinci** 2023-05-13 05:34 UTC
Labels: bug, duplicate
